### PR TITLE
Ensure 'name' field in image metadata during analysis

### LINKED ISSUE #86: analysis fails due to missing image metadata key
When running analysis I get this error:
```txt
celery_1    | [2022-08-11 08:25:00,953: INFO/MainProcess] Task optimal_transport_morphometry.core.tasks.run_utm[83ff07a7-4467-4bf0-919a-69d4fd2c41ec] received
celery_1    | [2022-08-11 08:25:00,962: ERROR/ForkPoolWorker-1] Task optimal_transport_morphometry.core.tasks.run_utm[83ff07a7-4467-4bf0-919a-69d4fd2c41ec] raised unexpected: KeyError('name')
celery_1    | Traceback (most recent call last):
celery_1    |   File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 451, in trace_task
celery_1    |     R = retval = fun(*args, **kwargs)
celery_1    |   File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 734, in __protected_call__
celery_1    |     return self.run(*args, **kwargs)
celery_1    |   File "/opt/django-project/optimal_transport_morphometry/core/tasks.py", line 155, in run_utm
celery_1    |     filename = f'{tmpdir}/{meta["name"]}'
celery_1    | KeyError: 'name'
```
It looks like `image.metadata` [here](https://github.com/girder/otm-server/blob/8d5453a61e80a01dcd2754d21c01c3316d55422e/optimal_transport_morphometry/core/tasks.py#L151) is supposed to have a key `name`.

### PR DESCRIPTION
**Pull request by AlmightyYakob**
Closes #86

This also updates the upload batch endpoint to return an error if the user tries to upload a batch that has no new images (i.e. if they tried to upload the same csv twice).

### CODE REVIEW

**Comment by AlmightyYakob** [comment]
@ebrahimebrahim before running anything, you'll need to run

```
docker-compose run --rm django ./manage.py migrate
```

to include the new db constraint.

**Comment by ebrahimebrahim** [comment]
When trying this locally, I now get:

```txt
celery_1    | [2022-08-12 19:47:37,457: INFO/MainProcess] Task optimal_transport_morphometry.core.tasks.run_utm[7d82da1d-ebe0-44a8-ab6b-84f392bea23c] received
celery_1    | [2022-08-12 19:47:37,464: ERROR/ForkPoolWorker-1] Task optimal_transport_morphometry.core.tasks.run_utm[7d82da1d-ebe0-44a8-ab6b-84f392bea23c] raised unexpected: KeyError('name')
celery_1    | Traceback (most recent call last):
celery_1    |   File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 451, in trace_task
celery_1    |     R = retval = fun(*args, **kwargs)
celery_1    |   File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 734, in __protected_call__
celery_1    |     return self.run(*args, **kwargs)
celery_1    |   File "/opt/django-project/optimal_transport_morphometry/core/tasks.py", line 152, in run_utm
celery_1    |     meta['name'].setdefault('name', image.name)
celery_1    | KeyError: 'name'
```

**Review by ebrahimebrahim — CHANGES_REQUESTED** [review]
When trying this locally, I now get:

```txt
celery_1    | [2022-08-12 19:47:37,457: INFO/MainProcess] Task optimal_transport_morphometry.core.tasks.run_utm[7d82da1d-ebe0-44a8-ab6b-84f392bea23c] received
celery_1    | [2022-08-12 19:47:37,464: ERROR/ForkPoolWorker-1] Task optimal_transport_morphometry.core.tasks.run_utm[7d82da1d-ebe0-44a8-ab6b-84f392bea23c] raised unexpected: KeyError('name')
celery_1    | Traceback (most recent call last):
celery_1    |   File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 451, in trace_task
celery_1    |     R = retval = fun(*args, **kwargs)
celery_1    |   File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 734, in __protected_call__
celery_1    |     return self.run(*args, **kwargs)
celery_1    |   File "/opt/django-project/optimal_transport_morphometry/core/tasks.py", line 152, in run_utm
celery_1    |     meta['name'].setdefault('name', image.name)
celery_1    | KeyError: 'name'
```

**Comment by AlmightyYakob** [comment]
> When trying this locally, I now get:
> 
> ```
> celery_1    | [2022-08-12 19:47:37,457: INFO/MainProcess] Task optimal_transport_morphometry.core.tasks.run_utm[7d82da1d-ebe0-44a8-ab6b-84f392bea23c] received
> celery_1    | [2022-08-12 19:47:37,464: ERROR/ForkPoolWorker-1] Task optimal_transport_morphometry.core.tasks.run_utm[7d82da1d-ebe0-44a8-ab6b-84f392bea23c] raised unexpected: KeyError('name')
> celery_1    | Traceback (most recent call last):
> celery_1    |   File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 451, in trace_task
> celery_1    |     R = retval = fun(*args, **kwargs)
> celery_1    |   File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 734, in __protected_call__
> celery_1    |     return self.run(*args, **kwargs)
> celery_1    |   File "/opt/django-project/optimal_transport_morphometry/core/tasks.py", line 152, in run_utm
> celery_1    |     meta['name'].setdefault('name', image.name)
> celery_1    | KeyError: 'name'
> ```

:facepalm: That was a dumb error on my part, it should be good now.

**Review by ebrahimebrahim — APPROVED** [review]

**Comment by ebrahimebrahim** [comment]
Analysis fully works for me now! Ready to merge

**Pull request merged**
