### PR TITLE
Add missing extra `worker` to celery Dockerfile

### LINKED ISSUE #76: Fix import error in preprocessing task
Preprocessing does not run, and I get the following from otm-server

```txt
django_1    | [16:15:42] WARNING  Bad Request: /api/v1/datasets/2/preprocess        log.py:224
django_1    |            WARNING  "POST /api/v1/datasets/2/preprocess          basehttp.py:161
django_1    |                     HTTP/1.1" 400 36        
```

### PR DESCRIPTION
**Pull request by AlmightyYakob**
Closes #76.

Since this addresses the root cause for #76, I'll close that issue with this PR, and make a new issue to address tasks more generally.

### CODE REVIEW

**Comment by AlmightyYakob** [comment]
I think this is because you reset your database, and so no longer have those in your database. Running the `populate_db` command should fix it.

Realistically we should update how we treat atlases. I've filed #80 for this.

**Comment by ebrahimebrahim** [comment]
Ah okay, thank you. I thought that `populate_db` was no longer needed since https://github.com/girder/otm-client/pull/15

@AlmightyYakob When I run `populate_db` it seems I'm forced to give it a CSV file. But I don't want to create a dataset with it, I just want to add the atlases to my database. I can create a dataset using the client. Should we for now add a simplified way of running `populate_db` that doesn't require providing a csv file, owner, etc?

Thanks for creating #80.

**Comment by AlmightyYakob** [comment]
> @AlmightyYakob When I run `populate_db` it seems I'm forced to give it a CSV file. But I don't want to create a dataset with it, I just want to add the atlases to my database. I can create a dataset using the client. Should we for now add a simplified way of running `populate_db` that doesn't require providing a csv file, owner, etc?

IMO I think we should split out the atlas creation from the `populate_db` command, and just deal with populating data in that command. The atlas creation can be done on its own. I guess all I'm saying is I think addressing #80 is the easiest way to solve both issues.

**Comment by ebrahimebrahim** [comment]
Got it, thanks for explaining.

**Pull request merged**
